### PR TITLE
add an example + update rdme

### PR DESCRIPTION
**Pull request by ctf0**
https://github.com/nao-pon/flysystem-google-drive/issues/2
https://github.com/nao-pon/flysystem-google-drive/issues/3

### CODE REVIEW

**Comment by nao-pon** [comment]
@ctf0 Thanks a lot! 👍

**Comment by ctf0** [comment]
sure thing, one last thing, plz correct the file name in the example link, i forgot to correct it

**Comment by nao-pon** [comment]
OK, I done. ;-) Thanks!

**Comment by ctf0** [comment]
awesome, thanx 💯

**Pull request merged**
